testeCloudFrontNextJS:
  stage: "temp"
  component: "@sls-next/serverless-component"
  inputs:
    bucketName: swp-dashboard-temp
    name: swp-dashboard-temp
    domain: "dashboard2.swipetech.com.br"
