name: Deploy main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_SECRET }}
          aws-region: us-east-1
          react-app-host: secrets.REACT_APP_HOST
          react-app-sdk-base-url: secrets.REACT_APP_SDK_BASE_URL
          react-app-sdk-secret: secrets.REACT_APP_SDK_SECRET
          react-app-sdk-api-key: secrets.REACT_APP_SDK_API_KEY
      - name: Verificar arquivos
        run: ls -la && cat .env
      - name: Deploy Next.js app
        run: npx serverless
      - name: Verificar arquivos novamente
        run: ls -la && cat .env
