name: Deploy main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_SECRET }}
          aws-region: us-east-1
      - name: Verificar arquivos prev
        run: ls -la && cat .env
      - name: Create env file
        run: |
          echo REACT_APP_HOST=${{ secrets.REACT_APP_HOST }} >> .env
          echo REACT_APP_SDK_BASE_URL=${{ secrets.REACT_APP_SDK_BASE_URL }} >> .env
          echo REACT_APP_SDK_SECRET=${{ secrets.REACT_APP_SDK_SECRET }} >> .env
          echo REACT_APP_SDK_API_KEY=${{ secrets.REACT_APP_SDK_API_KEY }} >> .env
          cat .env
      - name: Verificar arquivos
        run: ls -la && cat .env
      - name: Deploy Next.js app
        run: npx serverless
      - name: Verificar arquivos novamente
        run: ls -la && cat .env
